# Generated by Django 5.1.7 on 2025-03-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('cif', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
            ],
        ),
    ]
